seed = 100
model = "entity_typing"
save_state = "none"

[data]
train_dataset_path = "D:/Loisir/Code_python/LyRIDS_Opener/external/OWNER/data/lyrids/crossner_ai/train.json"
train_dataset_name = "crossner_ai"
test_dataset_path = "D:/Loisir/Code_python/LyRIDS_Opener/external/OWNER/data/lyrids/crossner_ai/test.json"
test_dataset_name = "crossner_ai"

[entity_typing]
template = "{sentence} {entity} is a [MASK]."
plm_name = "bert-base-uncased"
max_len = 256
batch_size = 8
num_epochs = 1
learning_rate = 2e-5
k_min = 2
k_max = 30
k_step = 2
